name: Deployment pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  SHOULD_DEPLOY: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.deployment.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run lint
      - name: Backend tests
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
      - name: Install frontend dependencies
        run: npm ci
        working-directory: bloglist
      - name: Frontend tests
        run: npm run test
        working-directory: bloglist
      - name: Install E2E dependencies
        run: npm ci
        working-directory: bloglist-e2e
      - name: Build frontend
        run: npm run build
        working-directory: bloglist
      - name: Copy frontend build to backend
        run: cp -r bloglist/dist dist
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: bloglist-e2e
      - name: Run E2E tests
        run: npx playwright test
        working-directory: bloglist-e2e
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: bloglist-e2e/playwright-report/
          retention-days: 30
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
      - name: Deploy to Fly.io
        id: deployment
        run: flyctl deploy --remote-only
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ needs.simple_deployment_pipeline.outputs.should_deploy == 'true'}}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
